App\Entity\AclResource:
    attributes:
        denormalization_context:
            groups: [ aclResource:write ]
        normalization_context:
            groups: [ exposed ]
        pagination_enabled: false
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        collection_query:
            pagination_enabled: false
