App\Entity\AclRole:
    normalizationContext:
        groups: [aclRole:read]
    #disable rest
    collectionOperations: {}
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        collection_query:
            pagination_enabled: false
            normalization_context: [aclRole:read]
        item_query:
        update:
            security: "is_granted('EDIT_ROLE')"
        create:
            security: "is_granted('CREATE_ROLE')"
            denormalization_context:
                groups:
                    - aclRole:write
                    - aclResource:write
            
        
