App\Entity\Group:
    attributes:
        denormalization_context:
            groups: [ group:write ]
        normalization_context:
            groups: [ exposed ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_EDIT'
            security: "is_granted('GROUP_EDIT')"
            normalization_context:
        update:
            security: "is_granted('GROUP_EDIT')"
            security_message: 'r: GROUP_EDIT'
        delete:
            security: "is_granted('GROUP_DELETE')"
            security_message: "r: GROUP_DELETE"
        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
