App\Entity\SubjectType:
    attributes:
        denormalization_context:
            groups: [ subjectType:write ]
        normalization_context:
            groups: [ exposed ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: SUBJECT_SHOW_ALL'
            security: "is_granted('SUBJECT_SHOW_ALL')"
        update:
            security: "is_granted('SUBJECT_SHOW_ALL')"
            security_message: 'r: SUBJECT_SHOW_ALL'

        item_query:
            security_message: "r: SUBJECT_SHOW_ALL"
            security: "is_granted('SUBJECT_SHOW_ALL')"

        collection_query:
            security: "is_granted('SUBJECT_SHOW_ALL')"
        delete:
            security: "is_granted('SUBJECT_DELETE')"
