App\Entity\Subject:
    attributes:
        denormalization_context:
            groups: [ subject:write ]
        normalization_context:
            groups: [ exposed ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
        
        edit:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"

        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
        
        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
        
        delete:
            security: "is_granted('SUBJECT_DELETE')"
