App\Entity\SubjectType:
    normalizationContext:
        groups: [ subject:read ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
            normalization_context:
                groups:
                    - subjectType:read
            denormalization_context:
                groups:
                    - subjectType:write

        update:
            security: "is_granted('GROUP_CREATE')"
            security_message: 'r: GROUP_CREATE'
            normalization_context:
                groups:
                    - subjectType:read
            denormalization_context:
                groups:
                    - subjectType:write
        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subjectType:read

        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subjectType:read

App\Entity\Subject:
    normalizationContext:
        groups: [ subject:read ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
            normalization_context:
                groups:
                    - subject:read
            denormalization_context:
                groups:
                    - subject:write
        edit:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
            normalization_context:
                groups:
                    - subject:read
            denormalization_context:
                groups:
                    - subject:write
        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subject:read
                    - subjectType:read

        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subject:read
                    - subjectType:read
                    - group:read
                    - classGroup:read
