App\Entity\Subject:
    #disable rest
    collectionOperations: {}
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
            normalization_context:
                groups:
                    - subject:read
            denormalization_context:
                groups:
                    - subject:write

        update:
            security: "is_granted('GROUP_CREATE')"
            security_message: 'r: GROUP_CREATE'
            normalization_context:
                groups:
                    - subject:read
            denormalization_context:
                groups:
                    - subject:write
        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subject:read

        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subject:read

App\Entity\SubjectHasGroup:
    #disable rest
    collectionOperations: {}
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_message: 'r: GROUP_CREATE'
            security: "is_granted('GROUP_CREATE')"
            normalization_context:
                groups:
                    - subjectHasGroup:read
            denormalization_context:
                groups:
                    - subjectHasGroup:write

        item_query:
            security_message: "r: GROUP_SHOW_ALL"
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subjectHasGroup:read

        collection_query:
            security: "is_granted('GROUP_SHOW_ALL')"
            normalization_context:
                groups:
                    - subjectHasGroup:read
