App\Entity\User:
    attributes:
    collectionOperations: {}
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        me:
            security_message: "r: USER_LOGGED"
            security: "is_granted('USER_LOGGED')"
            item_query: App\Controller\GetMeController
            args: []
            normalization_context:
                groups:
                    - user:read
                    - aclRole:read
        collection_query:
            security_message: "r: LIST_ALL_USERS"
            security: "is_granted('LIST_ALL_USERS')"
            normalization_context:
                groups:
                    - user:read
                    - aclRole:read
