App\Entity\User:
    attributes:
        security: 'is_granted("USER")'
    collectionOperations: {}
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        me:
            item_query: App\Controller\GetMeController
            args: []
