App\Entity\WebPushSubscribe:
    attributes:
        denormalization_context:
            groups: [ webPushSubscribe:write ]
        normalization_context:
            groups: [ exposed ]
    #disable rest
    collectionOperations: { }
    itemOperations:
        get:
            method: GET
            controller: ApiPlatform\Core\Action\NotFoundAction
            read: false
            output: false
    graphql:
        create:
            security_post_denormalize: "is_granted('IS_SAME_USER', object.getUser())"
        
