version: '3.4'

services:  
  app:
    container_name: loopr_app_dev
    build:
      context: ./app
      dockerfile: ../docker/app/dev/Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
      - /app/node_modules
      - /app/.next
      
  storybook:
    container_name: loopr_storbook
    build:
      context: ./app
      dockerfile: ../docker/app/dev/Dockerfile
    ports:
      - 3002:3002
    command: storybook --quiet
    volumes:
      - ./app:/app
