lexik_jwt_authentication:
    secret_key: '%env(base64:JWT_PRIVATE_KEY)%'
    public_key: '%env(base64:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    user_identity_field: id
    token_ttl: 604800
