version: '3.4'

x-cache-from:
  - &api-cache-from-testing
    cache_from:
      - ${NGINX_IMAGE:-quay.io/api-platform/nginx}
      - ${PHP_IMAGE:-quay.io/api-platform/php}

services:
  php:
    build:
      context: ../api
      target: api_platform_php
      <<: *api-cache-from-testing
    image: ${PHP_IMAGE:-quay.io/api-platform/php}
    depends_on:
      - db
    links:
      - db
    ports:
      - target: 9000
        published: 9002
    volumes:
      - ../api:/srv/api:rw,cached
      - ../api/docker/php/conf.d/api-platform.dev.ini:/usr/local/etc/php/conf.d/api-platform.ini

  db:
    image: postgres:12-alpine
    environment:
      - POSTGRES_DB=cz_loopr_app
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
    volumes:
      - db-data:/var/lib/postgresql/data:rw
    ports:
      - target: 5432
        published: 

volumes:
  db-data: {}
